"""Initial schema, frozen: see `design/DECISIONS.md` for why.

Revision ID: 0001
Revises:
Create Date: 2026-09-12

"""

import sqlalchemy as sa

from alembic import op
from app.db_views import create_share_owed_view, drop_share_owed_view

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create every table and its indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_trip_slug"),
    )
    op.create_index(op.f("ix_trip_slug"), "trip", ["slug"], unique=False)
    op.create_table(
        "label",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("name_norm", sa.String(length=40), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trip_id", "name_norm", name="uq_label_trip_norm"),
    )
    op.create_index(op.f("ix_label_name_norm"), "label", ["name_norm"], unique=False)
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("default_weight_scaled", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "trip_id", name="uq_person_id_trip"),
        sa.UniqueConstraint("trip_id", "name", name="uq_person_trip_name"),
    )
    op.create_table(
        "trip_country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "trip_id", name="uq_country_id_trip"),
        sa.UniqueConstraint("trip_id", "name", name="uq_country_trip_name"),
    )
    op.create_table(
        "trip_currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "trip_id", name="uq_currency_id_trip"),
        sa.UniqueConstraint("trip_id", "code", name="uq_currency_trip_code"),
    )
    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("tracked", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["person_id", "trip_id"], ["person.id", "person.trip_id"], name="fk_wallet_person_trip"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "trip_id", name="uq_wallet_id_trip"),
        sa.UniqueConstraint("person_id", "name", name="uq_wallet_person_name"),
    )
    op.create_index(op.f("ix_wallet_person_id"), "wallet", ["person_id"], unique=False)
    op.create_index(op.f("ix_wallet_trip_id"), "wallet", ["trip_id"], unique=False)
    op.create_table(
        "line_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("payer_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("map_url", sa.String(), nullable=True),
        sa.Column("lat", sa.String(length=20), nullable=True),
        sa.Column("lon", sa.String(length=20), nullable=True),
        sa.Column("split_mode", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["country_id", "trip_id"],
            ["trip_country.id", "trip_country.trip_id"],
            name="fk_item_country_trip",
        ),
        sa.ForeignKeyConstraint(
            ["currency_id", "trip_id"],
            ["trip_currency.id", "trip_currency.trip_id"],
            name="fk_item_currency_trip",
        ),
        sa.ForeignKeyConstraint(
            ["payer_id", "trip_id"], ["person.id", "person.trip_id"], name="fk_item_payer_trip"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id", "trip_id"], ["wallet.id", "wallet.trip_id"], name="fk_item_wallet_trip"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_line_item_country_id"), "line_item", ["country_id"], unique=False)
    op.create_index(op.f("ix_line_item_currency_id"), "line_item", ["currency_id"], unique=False)
    op.create_index(op.f("ix_line_item_occurred_at"), "line_item", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_line_item_payer_id"), "line_item", ["payer_id"], unique=False)
    op.create_index(op.f("ix_line_item_trip_id"), "line_item", ["trip_id"], unique=False)
    op.create_index(op.f("ix_line_item_wallet_id"), "line_item", ["wallet_id"], unique=False)
    op.create_table(
        "wallet_transfer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("from_wallet_id", sa.Integer(), nullable=False),
        sa.Column("from_currency_id", sa.Integer(), nullable=False),
        sa.Column("from_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("to_wallet_id", sa.Integer(), nullable=False),
        sa.Column("to_currency_id", sa.Integer(), nullable=False),
        sa.Column("to_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.CheckConstraint(
            "from_wallet_id <> to_wallet_id OR from_currency_id <> to_currency_id",
            name="ck_transfer_not_same",
        ),
        sa.ForeignKeyConstraint(
            ["from_currency_id", "trip_id"],
            ["trip_currency.id", "trip_currency.trip_id"],
            name="fk_transfer_from_currency_trip",
        ),
        sa.ForeignKeyConstraint(
            ["from_wallet_id", "trip_id"],
            ["wallet.id", "wallet.trip_id"],
            name="fk_transfer_from_wallet_trip",
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_id", "trip_id"],
            ["trip_currency.id", "trip_currency.trip_id"],
            name="fk_transfer_to_currency_trip",
        ),
        sa.ForeignKeyConstraint(
            ["to_wallet_id", "trip_id"],
            ["wallet.id", "wallet.trip_id"],
            name="fk_transfer_to_wallet_trip",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_transfer_from_wallet_id"),
        "wallet_transfer",
        ["from_wallet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_transfer_to_wallet_id"), "wallet_transfer", ["to_wallet_id"], unique=False
    )
    op.create_index(
        "ix_wallet_transfer_trip_occurred",
        "wallet_transfer",
        ["trip_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "item_label",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["line_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "label_id"),
    )
    op.create_table(
        "item_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("weight_scaled", sa.Integer(), nullable=False),
        sa.Column("owed_minor", sa.BigInteger(), nullable=True),
        sa.Column("split_mode_exact", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(split_mode_exact = false AND owed_minor IS NULL) "
            "OR (split_mode_exact = true AND owed_minor IS NOT NULL)",
            name="ck_share_exact_owed",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["line_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "person_id", name="uq_share_item_person"),
    )
    op.create_index(op.f("ix_item_share_item_id"), "item_share", ["item_id"], unique=False)
    op.create_index(op.f("ix_item_share_person_id"), "item_share", ["person_id"], unique=False)
    # ### end Alembic commands ###
    # Not autogenerated: share_owed is a raw view, kept out of SQLModel.metadata
    # so metadata.create_all never touches it.
    op.execute(create_share_owed_view)


def downgrade() -> None:
    """Drop the share-owed view and every table."""
    op.execute(drop_share_owed_view)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_share_person_id"), table_name="item_share")
    op.drop_index(op.f("ix_item_share_item_id"), table_name="item_share")
    op.drop_table("item_share")
    op.drop_table("item_label")
    op.drop_index("ix_wallet_transfer_trip_occurred", table_name="wallet_transfer")
    op.drop_index(op.f("ix_wallet_transfer_to_wallet_id"), table_name="wallet_transfer")
    op.drop_index(op.f("ix_wallet_transfer_from_wallet_id"), table_name="wallet_transfer")
    op.drop_table("wallet_transfer")
    op.drop_index(op.f("ix_line_item_wallet_id"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_trip_id"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_payer_id"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_occurred_at"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_currency_id"), table_name="line_item")
    op.drop_index(op.f("ix_line_item_country_id"), table_name="line_item")
    op.drop_table("line_item")
    op.drop_index(op.f("ix_wallet_trip_id"), table_name="wallet")
    op.drop_index(op.f("ix_wallet_person_id"), table_name="wallet")
    op.drop_table("wallet")
    op.drop_table("trip_currency")
    op.drop_table("trip_country")
    op.drop_table("person")
    op.drop_index(op.f("ix_label_name_norm"), table_name="label")
    op.drop_table("label")
    op.drop_index(op.f("ix_trip_slug"), table_name="trip")
    op.drop_table("trip")
    # ### end Alembic commands ###
