"""Add stays, and the nullable stay_id that groups items under one.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 13:32:10.118752

"""

import sqlalchemy as sa

from alembic import op
from app.db_views import create_share_owed_view, drop_share_owed_view

# revision identifiers, used by Alembic.
revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the stay table and point line_item at it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stay",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("map_url", sa.String(), nullable=True),
        sa.Column("lat", sa.String(length=20), nullable=True),
        sa.Column("lon", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["country_id", "trip_id"],
            ["trip_country.id", "trip_country.trip_id"],
            name="fk_stay_country_trip",
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], name=op.f("fk_stay_trip_id_trip")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stay")),
        sa.UniqueConstraint("id", "trip_id", name="uq_stay_id_trip"),
    )
    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stay_country_id"), ["country_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stay_trip_id"), ["trip_id"], unique=False)

    # Not autogenerated: SQLite cannot rebuild line_item while share_owed selects from it.
    op.execute(drop_share_owed_view)
    with op.batch_alter_table("line_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stay_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_line_item_stay_id"), ["stay_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_item_stay_trip", "stay", ["stay_id", "trip_id"], ["id", "trip_id"]
        )
    op.execute(create_share_owed_view)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop stay_id from line_item, then the stay table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_share_owed_view)
    with op.batch_alter_table("line_item", schema=None) as batch_op:
        batch_op.drop_constraint("fk_item_stay_trip", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_line_item_stay_id"))
        batch_op.drop_column("stay_id")
    op.execute(create_share_owed_view)

    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stay_trip_id"))
        batch_op.drop_index(batch_op.f("ix_stay_country_id"))

    op.drop_table("stay")
    # ### end Alembic commands ###
